jobs:
  - name: selchrome-manifest
    type: manifest
    steps:
     - IN: selchrome-python
     - IN: selchrome-test
     - TASK: managed

  - name: selchrome-deploy
    type: deploy
    steps:
      - IN: selchrome-manifest
      - IN: docker-opts-1
      - IN: selchrome
      - TASK: managed
        deployMethod: replace
